# Generated by Django 5.0.3 on 2024-03-30 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destinyapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TranscriptData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_id", models.CharField(max_length=100)),
                ("nearest_times", models.JSONField(default=dict)),
                ("transcript", models.CharField(max_length=1000000)),
                ("text_chunks", models.JSONField(default=dict)),
                ("summarized_chunks", models.JSONField(default=dict)),
            ],
        ),
        migrations.DeleteModel(name="Transcript",),
    ]
