# Generated by Django 5.0.3 on 2024-03-30 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destinyapp", "0002_transcriptdata_delete_transcript"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transcriptdata",
            name="text_chunks",
            field=models.JSONField(default=[]),
        ),
    ]
