# Generated by Django 5.0.3 on 2024-03-31 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destinyapp", "0004_alter_transcriptdata_text_chunks"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcriptdata",
            name="meta",
            field=models.CharField(default="", max_length=100000),
        ),
        migrations.AlterField(
            model_name="transcriptdata",
            name="transcript",
            field=models.CharField(default="", max_length=1000000),
        ),
    ]
