# Generated by Django 5.0.4 on 2024-05-30 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("destinyapp", "0008_transcriptdata_linked_transcript"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transcriptdata",
            old_name="nearest_times",
            new_name="raw_transcript_data",
        ),
    ]
