# Generated by Django 5.0.4 on 2024-06-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destinyapp", "0009_rename_nearest_times_transcriptdata_raw_transcript_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcriptdata",
            name="meta_markdown",
            field=models.CharField(default="", max_length=100000),
        ),
        migrations.AlterField(
            model_name="transcriptdata",
            name="meta",
            field=models.CharField(default="", max_length=1000000),
        ),
    ]
