# Generated by Django 5.0.4 on 2024-07-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destinyapp", "0010_transcriptdata_meta_markdown_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcriptdata",
            name="text_chunks_summary",
            field=models.JSONField(default=list),
        ),
    ]
