# Generated by Django 5.0.4 on 2024-07-05 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("destinyapp", "0011_transcriptdata_text_chunks_summary"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transcriptdata",
            old_name="text_chunks_summary",
            new_name="text_chunks_summaries",
        ),
    ]
