# Generated by Django 5.0.4 on 2024-07-05 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "destinyapp",
            "0012_rename_text_chunks_summary_transcriptdata_text_chunks_summaries",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="transcriptdata", old_name="meta", new_name="recap",
        ),
        migrations.RenameField(
            model_name="transcriptdata",
            old_name="meta_markdown",
            new_name="recap_markdown",
        ),
    ]
