# Generated by Django 5.0.4 on 2024-07-05 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("destinyapp", "0013_rename_meta_transcriptdata_recap_and_more"),
    ]

    operations = [
        migrations.RenameModel(old_name="TranscriptData", new_name="StreamRecapData",),
    ]
