# Generated by Django 5.0.4 on 2024-07-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destinyapp", "0015_streamrecapdata_chunk_annotations_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="streamrecapdata",
            name="plot_image",
            field=models.CharField(default="", max_length=2000000),
        ),
    ]
