# Generated by Django 5.0.4 on 2024-07-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destinyapp", "0017_alter_streamrecapdata_chunk_annotations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="streamrecapdata",
            name="plot_clickable_area_data",
            field=models.JSONField(default=list),
        ),
    ]
