# Generated by Django 5.0.4 on 2024-07-31 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destinyapp", "0018_alter_streamrecapdata_plot_clickable_area_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="streamrecapdata",
            name="plot_object",
            field=models.JSONField(default=dict),
        ),
    ]
