# Generated by Django 5.0.4 on 2024-08-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destinyapp", "0019_streamrecapdata_plot_object"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyRecapData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("applied_date", models.DateTimeField(default="")),
                ("video_ids", models.JSONField(default=list)),
                ("week_hook", models.CharField(default="", max_length=1000000)),
                ("week_recap", models.CharField(default="", max_length=1000000)),
                ("week_image", models.CharField(default="", max_length=2000000)),
                ("plot_image", models.CharField(default="", max_length=2000000)),
                ("plot_object", models.JSONField(default=dict)),
            ],
        ),
    ]
