# Generated by Django 5.0.4 on 2024-08-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destinyapp", "0020_weeklyrecapdata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weeklyrecapdata",
            name="applied_date",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
