# Generated by Django 5.0.4 on 2024-08-21 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destinyapp", "0021_alter_weeklyrecapdata_applied_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="weeklyrecapdata",
            name="earliest_date",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="weeklyrecapdata",
            name="stream_dates",
            field=models.JSONField(default=dict),
        ),
    ]
