# Generated by Django 5.0.4 on 2024-09-05 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destinyapp", "0022_weeklyrecapdata_earliest_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FastRecapData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_id", models.CharField(max_length=100)),
                ("plot_object", models.JSONField(default=dict)),
            ],
        ),
        migrations.AlterField(
            model_name="weeklyrecapdata",
            name="earliest_date",
            field=models.JSONField(default=""),
        ),
    ]
